### ISSUE TITLE
Max with paramater in plugin?

### ISSUE THREAD

**Issue by jjnxpct** [widgetfactory/wf_responsive_widgets#7]
Maybe it would be nice to have a max-width setting in the plugin?

**Comment by jjnxpct** [comment]
Or can we somehow do this with CSS? I can set the max-width, but then the height won't match...

**Comment by ryandemmer** [comment]
You can use css to set a max-width for the container, eg:
```css
.wf-responsive-iframe-container,
.wf-responsive-object-container,
.wf-responsive-embed-container,
.wf-responsive-video-container {
    max-width: 400px;
}
```
